###############################################################################
# R (http://r-project.org/) Event Class Model
#
# Copyright (c) 2015
# Gei Lin
#
# $Id$
#
###############################################################################


#' Save and Load all event definitions
#'
#' Saves (loads) the .event environment to (from) disk.
#'
#' After you have defined some events, you can use \code{saveEvents}
#' to save the entire .event environment to disk.
#'
#' \code{loadEvents} will read a file that contains events and add
#' those event definitions to your .event environment.
#' \code{reloadEvents} will remove all instruments in the current
#' .event environment before loading instruments from disk.
#'
#' The \code{file_name} should have a file extension of \dQuote{RData},
#' \dQuote{rda}, \dQuote{R}, or \dQuote{txt}.  If the \code{file_name} does not
#' end with one of those, \dQuote{.RData} will be appended to the
#' \code{file_name}
#'
#' If the file extension is \dQuote{R} or \dQuote{txt}, \code{saveEvents}
#' will create a text file of \R code that can be \code{\link{source}}d to
#' load instruments back into the .event environment.
#'
#' @aliases saveEvents loadEvents
#' @param file_name name of file. e.g. \dQuote{MyEvents.RData}.
#' As an experimental feature, a \code{list} or \code{environment} can be passed
#' to \code{file_name}.
#' @param dir Directory of file (defaults to current working directory. ie. "")
#' @param compress argument passed to \code{\link{save}}, default is "gzip"
#' @return Called for side-effect
#' @author Gei Lin
#' @seealso save, load load.instrument define_auctions, define_futures,
#' define_options (option_series.yahoo)
#' @examples
#' \dontrun{
#' Auction("US.10YR.FIX", Region("US"), 1)
#' tmpdir <- tempdir()
#' saveEvents("MyEvents.RData", dir=tmpdir)
#' rm_events(keep.regions=FALSE)
#' loadEvents("MyEvents.RData", dir=tmpdir)
#' # write .R file that can be sourced
#' saveEvents("MyEvents.R", dir=tmpdir)
#' rm_events(keep.regions=FALSE)
#' loadEvents("MyEvents.R", dir=tmpdir)
#' #source(file=paste(tmpdir, "MyEvents.R", sep="/")) # same
#' unlink(tmpdir, recursive=TRUE)
#' }
#' @export
#' @rdname saveEvents
saveEvents <- function(file_name="MyEvents", dir="", compress="gzip") {
  if (!is.null(dir) && !dir == "" && substr(dir,nchar(dir),nchar(dir)) != "/")
    dir <- paste(dir,"/",sep="")
  ssfn <- strsplit(file_name, "\\.")[[1]]
  extension <- if (tolower(tail(ssfn, 1)) %in% c('rda', 'rdata', 'r', 'txt')) {
    file_name <- paste(ssfn[1:(length(ssfn)-1)], collapse=".")
    tail(ssfn, 1)
  } else "RData"
  file.name <- paste(dir, file_name, ".", extension, sep="")
  # if extension is "R", "r", or "txt" create a file that can be sourced
  if (tolower(extension) %in% c("r", "txt")) {
    cat("#auto-generated by FinancialEvent:::saveEvents\n\n",
        "require(FinancialEvent)\n\n", file=file.name)
    for (s in ls_events()) {
      sink(file.name, append=TRUE)
      cat('assign("', s, '", pos=FinancialEvent:::.event, ',
          'value=\n', sep="", append=TRUE)
      dput(getEvent(s))
      cat(")\n\n", append=TRUE)
      sink()
      #system(paste("cat", file.name)) #for debugging
    }
  } else save(.event, file = file.name, compress=compress)
}


#' @export
#' @rdname saveEvents
loadEvents <-function(file_name="MyEvents", dir="") {
  require("utils")
  if (is.environment(file_name) || is.list(file_name)) {
    ilist <- as.list(file_name)
    if (!all(vapply(ilist, function(x) length(x[["primary_id"]]) == 1L,
                    TRUE))) {
      stop("all events must have exactly one primary_id")
    }
    for (i in seq_along(ilist)) {
      assign(ilist[[i]][["primary_id"]], ilist[[i]],
             pos=.event)
    }
    return(invisible(NULL))
  }
  if (!is.null(dir) && !dir == "" && substr(dir,nchar(dir),nchar(dir)) != "/")
    dir <- paste(dir,"/",sep="")
  ssfn <- strsplit(file_name, "\\.")[[1]]
  extension <- if (tolower(tail(ssfn, 1)) %in% c('rda', 'rdata', 'r', 'txt')) {
    file_name <- paste(ssfn[1:(length(ssfn)-1)], collapse=".")
    tail(ssfn, 1)
  } else "RData"
  file.name <- paste(dir, file_name, ".", extension, sep="")
  if (tolower(extension) %in% c("r", "txt")) {
    if (substr(readLines(file.name, 1L), 1, 5) != "#auto") {
      warning(paste(file.name, "was not created by 'saveEvents'"))
    }
    source(file.name)
  } else {
    tmpenv <- new.env()
    load(paste(dir,file_name,".",extension,sep=""),envir=tmpenv)
    il <- ls(tmpenv$.event, all.names=TRUE)
    for (i in il) {
      assign(i, tmpenv$.event[[i]],
             pos=.event, inherits=FALSE)
    }
  }
}


#' @export
#' @rdname saveEvents
reloadEvents <- function(file_name="MyEvents", dir="") {
  rm_events(keep.regions=FALSE)
  loadEvents(file_name=file_name, dir=dir)
}